server:
  port: 8080

spring:
  application:
    name: hn-gateway-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: hn-core-service
              uri: http://localhost:8081
              predicates:
                Path=${app.api-prefix}/core/**
              filters:
                - RewritePath=/api/v1/core/(?<segment>.*), /${segment}   #  → biến /core/xxx thành /xx
            # PRODUCT SERVICE
            - id: hn-product-service
              uri: http://localhost:8082
              predicates:
                - Path=${app.api-prefix}/product/**
              filters:
                - RewritePath=/api/v1/product/(?<segment>.*), /${segment}

            # INVENTORY SERVICE
            - id: hn-inventory-service
              uri: http://localhost:8083
              predicates:
                - Path=${app.api-prefix}/inventory/**
              filters:
                - RewritePath=/api/v1/inventory/(?<segment>.*), /${segment}

            # ORDER SERVICE
            - id: hn-order-service
              uri: http://localhost:8084
              predicates:
                - Path=${app.api-prefix}/order/**
              filters:
                - RewritePath=/api/v1/order/(?<segment>.*), /${segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
app:
  api-prefix: /api/v1